const AUTO_NAME_PATTERN = /^writ-(\d{13,})$/;

export function abbreviateTitle(title: string): string {
  const match = title.match(AUTO_NAME_PATTERN);
  if (!match) return title;
  const digits = match[1];
  return `writ-${digits.slice(-4)}`;
}

export function isAutoGeneratedTitle(title: string): boolean {
  return AUTO_NAME_PATTERN.test(title);
}
