import { describe, it, expect } from "vitest";
import { abbreviateTitle, isAutoGeneratedTitle } from "../../lib/buffer-name";

describe("abbreviateTitle", () => {
  it("abbreviates 13-digit writ timestamp to writ-<last4>", () => {
    expect(abbreviateTitle("writ-1778473041613")).toBe("writ-1613");
  });

  it("abbreviates longer timestamps to writ-<last4>", () => {
    expect(abbreviateTitle("writ-99999999999999")).toBe("writ-9999");
  });

  it("preserves user-renamed titles", () => {
    expect(abbreviateTitle("my notes")).toBe("my notes");
    expect(abbreviateTitle("scratch.md")).toBe("scratch.md");
  });

  it("preserves writ titles shorter than 13 digits", () => {
    expect(abbreviateTitle("writ-12345")).toBe("writ-12345");
    expect(abbreviateTitle("writ-1234567890123")).toBe("writ-0123");
  });

  it("preserves writ titles with non-digit suffix", () => {
    expect(abbreviateTitle("writ-1778473041613-foo")).toBe("writ-1778473041613-foo");
    expect(abbreviateTitle("writ-notes")).toBe("writ-notes");
  });

  it("preserves titles that just happen to start with writ", () => {
    expect(abbreviateTitle("written-notes")).toBe("written-notes");
  });
});

describe("isAutoGeneratedTitle", () => {
  it("returns true for 13-digit writ timestamps", () => {
    expect(isAutoGeneratedTitle("writ-1778473041613")).toBe(true);
  });

  it("returns false for user-renamed titles", () => {
    expect(isAutoGeneratedTitle("my notes")).toBe(false);
    expect(isAutoGeneratedTitle("writ-notes")).toBe(false);
  });

  it("returns false for short numeric suffixes", () => {
    expect(isAutoGeneratedTitle("writ-1234")).toBe(false);
  });
});
