import { describe, it, expect } from "vitest";
import { readFileSync, readdirSync } from "node:fs";
import { resolve } from "node:path";
import { COLORS, LEGACY_FROZEN, TYPE } from "../../styles/generated/tokens";

const ROOT = process.cwd();

const GENERATED = [
  "src/styles/generated/theme.css",
  "src/styles/generated/legacy-aliases.css",
  "src/styles/generated/tokens.ts",
  "src-tauri/assets/generated/preview-tokens.css",
  "site/design-system/generated/tokens.css",
];

const THEME_CSS = readFileSync(resolve(ROOT, "src/styles/generated/theme.css"), "utf8");
const LEGACY_CSS = readFileSync(resolve(ROOT, "src/styles/generated/legacy-aliases.css"), "utf8");

const ACCENT_IDS = ["pine", "writ-blue", "terracotta", "slate", "plum", "gold"];

// Every custom property the baseline declares on the light root.
const BASELINE_ROOT_TOKENS = [
  "--writ-font-ui",
  "--writ-font-prose",
  "--writ-font-prose-alt",
  "--writ-font-mono",
  "--writ-ui-xs",
  "--writ-ui-xs-lh",
  "--writ-ui-sm",
  "--writ-ui-sm-lh",
  "--writ-ui-md",
  "--writ-ui-md-lh",
  "--writ-ui-lg",
  "--writ-ui-lg-lh",
  "--writ-ui-tracking",
  "--writ-prose-size",
  "--writ-prose-lh",
  "--writ-prose-measure",
  "--writ-prose-pad-x",
  "--writ-prose-pad-y",
  "--writ-prose-p-spacing",
  "--writ-heading-spacing",
  "--writ-heading-color",
  "--writ-heading-formatting",
  "--writ-h1-size",
  "--writ-h1-weight",
  "--writ-h1-lh",
  "--writ-h2-size",
  "--writ-h2-weight",
  "--writ-h2-lh",
  "--writ-h3-size",
  "--writ-h3-weight",
  "--writ-h3-lh",
  "--writ-h4-size",
  "--writ-h4-weight",
  "--writ-h4-lh",
  "--writ-h5-size",
  "--writ-h5-weight",
  "--writ-h5-lh",
  "--writ-h6-size",
  "--writ-h6-weight",
  "--writ-h6-lh",
  "--writ-bg-canvas",
  "--writ-bg-sidebar",
  "--writ-bg-raised",
  "--writ-bg-sunken",
  "--writ-bg-hover",
  "--writ-bg-selected",
  "--writ-border",
  "--writ-border-soft",
  "--writ-fg",
  "--writ-fg-muted",
  "--writ-fg-faint",
  "--writ-danger",
  "--writ-switch-off",
  "--writ-syn-string",
  "--writ-shadow-popover",
  "--writ-shadow-modal",
  "--writ-shadow-chip",
  "--writ-accent",
  "--writ-accent-hover",
  "--writ-accent-fg",
  "--writ-r-row",
  "--writ-r-control",
  "--writ-r-tab",
  "--writ-r-popover",
  "--writ-r-modal",
  "--writ-r-card",
  "--writ-r-media",
  "--writ-r-pill",
  "--writ-r-window",
  "--writ-icon-size",
  "--writ-icon-color",
  "--writ-icon-opacity",
  "--writ-icon-opacity-hover",
  "--writ-sidebar-width",
  "--writ-sidebar-min-width",
  "--writ-sidebar-max-width",
  "--writ-sidebar-row-pitch",
  "--writ-sidebar-row-fill",
  "--writ-space-1",
  "--writ-space-2",
  "--writ-space-3",
  "--writ-space-4",
  "--writ-space-5",
  "--writ-space-6",
  "--writ-space-7",
  "--writ-ease",
  "--writ-motion-fast",
  "--writ-motion-duration",
  "--writ-motion-slow",
  "--writ-motion",
  "--writ-z-base",
  "--writ-z-chrome",
  "--writ-z-popover",
  "--writ-z-palette",
  "--writ-z-modal",
  "--writ-z-toast",
  "--writ-z-drag",
];

function blockBody(css: string, selector: string): string {
  const start = css.indexOf(`${selector} {`);
  if (start === -1) throw new Error(`no block for ${selector}`);
  const open = css.indexOf("{", start);
  const close = css.indexOf("\n}", open);
  return css.slice(open + 1, close);
}

function declarationsIn(body: string): Map<string, string> {
  const out = new Map<string, string>();
  for (const line of body.split("\n")) {
    const m = /^\s*(--[a-z0-9-]+)\s*:\s*(.+);\s*$/.exec(line);
    if (m) out.set(m[1], m[2]);
  }
  return out;
}

const ROOT_DECLS = declarationsIn(blockBody(THEME_CSS, ":root"));
const DARK_DECLS = declarationsIn(blockBody(THEME_CSS, ':root[data-theme="dark"]'));

describe("generated token outputs", () => {
  it("every generated file carries the do-not-edit banner", () => {
    for (const file of GENERATED) {
      const text = readFileSync(resolve(ROOT, file), "utf8");
      const banner = file.endsWith(".ts")
        ? "// Generated by design/tokens — run `pnpm tokens:build`. Do not edit."
        : "/* Generated by design/tokens — run `pnpm tokens:build`. Do not edit. */";
      expect(text.startsWith(banner), `${file} is missing the banner`).toBe(true);
    }
  });

  it("theme.css defines the full baseline token set on :root", () => {
    const missing = BASELINE_ROOT_TOKENS.filter((name) => !ROOT_DECLS.has(name));
    expect(missing, `missing from :root: ${missing.join(", ")}`).toEqual([]);
  });

  it("states the prose measure in px, because the app root is not 16px", () => {
    // global.css sets `html, body { font-size: var(--writ-ui-md) }`, so 1rem is
    // 13px in this app and the baseline 44rem would draw a 572px column. The
    // measure is absolute so the reading column is the 704px the baseline draws.
    expect(ROOT_DECLS.get("--writ-ui-md")).toBe("13px");
    expect(ROOT_DECLS.get("--writ-prose-measure")).toBe("704px");
    for (const [platform, type] of Object.entries(TYPE)) {
      expect(type.prose.measure, `${platform} prose measure`).toBe("704px");
    }
  });

  it("dark scheme redefines every colour token light defines", () => {
    const colorTokens = [
      "--writ-bg-canvas",
      "--writ-bg-sidebar",
      "--writ-bg-raised",
      "--writ-bg-sunken",
      "--writ-bg-hover",
      "--writ-bg-selected",
      "--writ-border",
      "--writ-border-soft",
      "--writ-fg",
      "--writ-fg-muted",
      "--writ-fg-faint",
      "--writ-danger",
      "--writ-switch-off",
      "--writ-syn-string",
      "--writ-shadow-popover",
      "--writ-shadow-modal",
      "--writ-shadow-chip",
      "--writ-accent",
      "--writ-accent-hover",
      "--writ-accent-fg",
    ];
    for (const name of colorTokens) {
      expect(DARK_DECLS.has(name), `${name} is not redefined for dark`).toBe(true);
      expect(DARK_DECLS.get(name)).not.toBe(ROOT_DECLS.get(name));
    }
  });

  it("each accent id defines base, hover and foreground in both schemes", () => {
    for (const id of ACCENT_IDS) {
      for (const selector of [
        `:root[data-accent="${id}"]`,
        `:root[data-accent="${id}"][data-theme="dark"]`,
      ]) {
        const decls = declarationsIn(blockBody(THEME_CSS, selector));
        expect([...decls.keys()].sort()).toEqual([
          "--writ-accent",
          "--writ-accent-fg",
          "--writ-accent-hover",
        ]);
      }
    }
  });

  it("the syntax set is the neutrals, so it follows the polarity", () => {
    // ADR-030 decision 3: only strings carry a hue. The names stay, so a
    // terminal preset still paints its own syntax colours at runtime.
    expect(ROOT_DECLS.get("--writ-syntax-keyword")).toBe("var(--writ-fg)");
    expect(ROOT_DECLS.get("--writ-syntax-comment")).toBe("var(--writ-fg-faint)");
    expect(ROOT_DECLS.get("--writ-syntax-string")).toBe("var(--writ-syn-string)");
  });

  it("pine light hover is #1C6453 and dark hover is #6BCBB0", () => {
    expect(declarationsIn(blockBody(THEME_CSS, ':root[data-accent="pine"]')).get("--writ-accent-hover")).toBe("#1C6453");
    expect(
      declarationsIn(blockBody(THEME_CSS, ':root[data-accent="pine"][data-theme="dark"]')).get(
        "--writ-accent-hover",
      ),
    ).toBe("#6BCBB0");
    expect(ROOT_DECLS.get("--writ-accent-hover")).toBe("#1C6453");
    expect(DARK_DECLS.get("--writ-accent-hover")).toBe("#6BCBB0");
  });

  it("reduced-motion block zeroes all three durations", () => {
    const media = THEME_CSS.slice(THEME_CSS.indexOf("@media (prefers-reduced-motion: reduce)"));
    expect(media).toContain("--writ-motion-fast: 0ms;");
    expect(media).toContain("--writ-motion-duration: 0ms;");
    expect(media).toContain("--writ-motion-slow: 0ms;");
  });

  it("tokens.ts COLORS and theme.css agree token-for-token", () => {
    const pairs: [keyof (typeof COLORS)["light"], string][] = [
      ["bgCanvas", "--writ-bg-canvas"],
      ["bgSidebar", "--writ-bg-sidebar"],
      ["bgRaised", "--writ-bg-raised"],
      ["bgSunken", "--writ-bg-sunken"],
      ["bgHover", "--writ-bg-hover"],
      ["bgSelected", "--writ-bg-selected"],
      ["border", "--writ-border"],
      ["borderSoft", "--writ-border-soft"],
      ["fg", "--writ-fg"],
      ["fgMuted", "--writ-fg-muted"],
      ["fgFaint", "--writ-fg-faint"],
      ["danger", "--writ-danger"],
      ["switchOff", "--writ-switch-off"],
      ["synString", "--writ-syn-string"],
    ];
    for (const [key, name] of pairs) {
      expect(COLORS.light[key], `light ${name}`).toBe(ROOT_DECLS.get(name));
      expect(COLORS.dark[key], `dark ${name}`).toBe(DARK_DECLS.get(name));
    }
  });
});

describe("legacy re-declarations", () => {
  // Written out, not recomputed: a name that starts being declared by both
  // sheets has to be added here on purpose, with the migration it implies.
  // The visual flip took the last of these off the legacy layer: every name the
  // new vocabulary also declares now resolves to the ADR-030 value. Adding one
  // back means freezing a token the design system owns, which needs a reason.
  const EXPECTED_LEGACY_FROZEN: string[] = [];

  function declaredNames(css: string): Set<string> {
    return new Set([...css.matchAll(/^\s*(--[a-z0-9-]+)\s*:/gm)].map((m) => m[1]));
  }

  it("the generated sheets declare exactly the reviewed set of names twice", () => {
    const inTheme = declaredNames(THEME_CSS);
    const overlap = [...declaredNames(LEGACY_CSS)].filter((name) => inTheme.has(name)).sort();
    expect(overlap, "a name is declared by both sheets without being reviewed").toEqual(
      EXPECTED_LEGACY_FROZEN,
    );
  });

  it("LEGACY_FROZEN exports that set", () => {
    expect([...LEGACY_FROZEN].sort()).toEqual(EXPECTED_LEGACY_FROZEN);
  });
});

describe("DTCG preset sources", () => {
  // Every preset src/styles/themes ships. A runtime preset with no DTCG source
  // is a palette outside the token pipeline, which is the thing ADR-030 exists
  // to stop, so this list is the file listing rather than a subset of it.
  const PRESET_IDS = readdirSync(resolve(ROOT, "src/styles/themes"))
    .filter((name) => name.endsWith(".json"))
    .map((name) => name.replace(/\.json$/, ""))
    .sort();
  const GROUPS = ["surface", "foreground", "border", "accent", "status", "syntax"] as const;

  it("cover every preset the app ships", () => {
    expect(PRESET_IDS).toContain("writ-light");
    expect(PRESET_IDS).toContain("writ-dark");
    expect(PRESET_IDS.length).toBe(8);
  });

  it("carry the same values as the runtime preset JSON", () => {
    for (const id of PRESET_IDS) {
      const dtcg = JSON.parse(readFileSync(resolve(ROOT, `design/tokens/preset/${id}.json`), "utf8"))
        .preset[id];
      const runtime = JSON.parse(
        readFileSync(resolve(ROOT, `src/styles/themes/${id}.json`), "utf8"),
      ) as { polarity: string } & Record<string, unknown>;
      expect(dtcg.polarity.$value, `${id} polarity`).toBe(runtime.polarity);
      for (const group of GROUPS) {
        for (const [key, value] of Object.entries(runtime[group] as Record<string, string>)) {
          expect(dtcg[group][key].$value, `${id}.${group}.${key}`).toBe(value);
        }
      }
    }
  });
});
