import StyleDictionary from "style-dictionary";

const BANNER_CSS = "/* Generated by design/tokens — run `pnpm tokens:build`. Do not edit. */";
const BANNER_TS = "// Generated by design/tokens — run `pnpm tokens:build`. Do not edit.";

// Leading path segments that address a layer (polarity, platform, alias set)
// rather than the token itself, and so never reach the CSS name.
const NAME_DROP = { base: 1, color: 2, platform: 3, preview: 2, preset: 2 };

function value(token) {
  return token.$value ?? token.value;
}

function nameParts(token) {
  return token.path.slice(NAME_DROP[token.path[0]] ?? 0);
}

function cssName(token, prefix) {
  const explicit = token.$extensions?.writ?.cssName;
  if (explicit) return explicit.replace(/^--writ-/, prefix);
  return prefix + nameParts(token).join("-");
}

function camelCase(parts) {
  return parts
    .map((part, i) => (i === 0 ? part : part[0].toUpperCase() + part.slice(1)))
    .join("")
    .replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase());
}

function shadowToCss(layers) {
  return (Array.isArray(layers) ? layers : [layers])
    .map((l) =>
      [l.offsetX, l.offsetY, l.blur, l.spread, l.color].filter((p) => p !== undefined).join(" "),
    )
    .join(", ");
}

// DTCG 2025.10 carries a dimension or duration as { value, unit }; CSS wants the
// two concatenated, with the unit the token declares rather than a forced px.
StyleDictionary.registerTransform({
  name: "value/dimension-css",
  type: "value",
  filter: (token) => ["dimension", "duration"].includes(token.$type ?? token.type),
  transform: (token) => {
    const raw = value(token);
    if (raw === null || typeof raw !== "object") return raw;
    return `${raw.value}${raw.unit ?? ""}`;
  },
});

StyleDictionary.registerTransform({
  name: "value/shadow-css",
  type: "value",
  filter: (token) => (token.$type ?? token.type) === "shadow",
  transform: (token) => shadowToCss(value(token)),
});

StyleDictionary.registerTransform({
  name: "name/writ-css",
  type: "name",
  transform: (token) => cssName(token, "--writ-"),
});

StyleDictionary.registerTransform({
  name: "name/writ-preview-css",
  type: "name",
  transform: (token) => cssName(token, "--writ-preview-"),
});

StyleDictionary.registerTransform({
  name: "name/writ-ts",
  type: "name",
  transform: (token) => camelCase(nameParts(token)),
});

function under(tokens, ...prefix) {
  return tokens.filter((token) => prefix.every((segment, i) => token.path[i] === segment));
}

// The eight UI type steps, which the CSS states as ratios of --writ-ui-size
// rather than as pixels. `size` itself and `tracking` keep their own values.
const UI_STEP_KEYS = new Set(["xs", "xs-lh", "sm", "sm-lh", "md", "md-lh", "lg", "lg-lh"]);
const UI_ROOT_NAME = "--writ-ui-size";

function pixels(raw) {
  const n = Number(String(raw).replace(/px$/, ""));
  if (!Number.isFinite(n)) throw new Error(`ui step ${raw} is not a pixel length`);
  return n;
}

/**
 * A UI step as a ratio of the root size, or null for any other token.
 *
 * The numerator is the step's own default and the denominator is the default
 * root of the same layer, so each platform keeps the proportions it was drawn
 * with: Windows resolves its 12px rows to 12px at a 14px root, and a user who
 * moves the root carries those proportions with them.
 */
function uiStepRatio(token, layer) {
  const path = token.path;
  if (path[path.length - 2] !== "ui") return null;
  const key = path[path.length - 1];
  if (!UI_STEP_KEYS.has(key)) return null;
  const rootPath = [...path.slice(0, -1), "size"].join(".");
  const root = layer.find((other) => other.path.join(".") === rootPath);
  if (!root) throw new Error(`${path.join(".")} has no sibling ui.size to scale against`);
  return `calc(var(${UI_ROOT_NAME}) * ${pixels(value(token))} / ${pixels(value(root))})`;
}

function declarations(tokens) {
  return tokens
    .map((token) => `  ${token.name}: ${uiStepRatio(token, tokens) ?? value(token)};`)
    .join("\n");
}

function block(selector, tokens) {
  if (tokens.length === 0) return "";
  return `${selector} {\n${declarations(tokens)}\n}\n`;
}

function sheet(blocks) {
  return `${BANNER_CSS}\n\n${blocks.filter((part) => part !== "").join("\n")}`;
}

function objectKey(key) {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(key) ? key : quote(key);
}

const ACCENT_IDS = ["pine", "writ-blue", "terracotta", "slate", "plum", "gold"];
const DEFAULT_ACCENT = "pine";
const PLATFORM_IDS = ["mac", "win", "linux"];

StyleDictionary.registerFormat({
  name: "css/writ-theme",
  format: ({ dictionary }) => {
    const all = dictionary.allTokens;
    const parts = [
      block(":root", [
        ...under(all, "base"),
        ...under(all, "status"),
        ...under(all, "syntax"),
        ...under(all, "traffic"),
        ...under(all, "color", "light"),
        ...under(all, "accent", DEFAULT_ACCENT, "light"),
      ]),
      block(':root[data-theme="dark"]', [
        ...under(all, "color", "dark"),
        ...under(all, "accent", DEFAULT_ACCENT, "dark"),
      ]),
    ];

    for (const platform of PLATFORM_IDS) {
      if (platform === "mac") continue;
      parts.push(
        block(`:root[data-platform="${platform}"]`, [
          ...under(all, "platform", platform, "shared"),
          ...under(all, "platform", platform, "light"),
        ]),
        block(
          `:root[data-platform="${platform}"][data-theme="dark"]`,
          under(all, "platform", platform, "dark"),
        ),
      );
    }

    for (const accent of ACCENT_IDS) {
      parts.push(
        block(`:root[data-accent="${accent}"]`, under(all, "accent", accent, "light")),
        block(
          `:root[data-accent="${accent}"][data-theme="dark"]`,
          under(all, "accent", accent, "dark"),
        ),
      );
    }

    parts.push(
      "@media (prefers-reduced-motion: reduce) {\n" +
        "  :root {\n" +
        "    --writ-motion-fast: 0ms;\n" +
        "    --writ-motion-duration: 0ms;\n" +
        "    --writ-motion-slow: 0ms;\n" +
        "  }\n" +
        "}\n",
    );

    return sheet(parts);
  },
});

StyleDictionary.registerFormat({
  name: "css/writ-preview",
  format: ({ dictionary }) => {
    const all = dictionary.allTokens;
    // Light is the default, and both polarities also get an attribute block:
    // the bridge flips an already-loaded document by setting the attribute, so
    // light has to be reachable that way and not only by its absence.
    return sheet([
      block(":root", under(all, "preview", "light")),
      block('[data-writ-theme="light"]', under(all, "preview", "light")),
      block('[data-writ-theme="dark"]', under(all, "preview", "dark")),
    ]);
  },
});

StyleDictionary.registerFormat({
  name: "css/writ-site",
  format: ({ dictionary }) => {
    const all = dictionary.allTokens;
    return sheet([
      block(":root", [
        ...under(all, "base"),
        ...under(all, "color", "light"),
        ...under(all, "accent", DEFAULT_ACCENT, "light"),
      ]),
      block("[data-theme='dark']", [
        ...under(all, "color", "dark"),
        ...under(all, "accent", DEFAULT_ACCENT, "dark"),
      ]),
    ]);
  },
});

function tsLookup(dictionary) {
  const byPath = new Map(dictionary.allTokens.map((token) => [token.path.join("."), token]));
  return (path) => {
    const token = byPath.get(path);
    if (!token) throw new Error(`token ${path} is missing from design/tokens`);
    return value(token);
  };
}

function quote(text) {
  return JSON.stringify(String(text));
}

function colorTokens(get, polarity) {
  const at = (suffix) => quote(get(`color.${polarity}.${suffix}`));
  return [
    `    bgCanvas: ${at("bg.canvas")},`,
    `    bgSidebar: ${at("bg.sidebar")},`,
    `    bgRaised: ${at("bg.raised")},`,
    `    bgSunken: ${at("bg.sunken")},`,
    `    bgHover: ${at("bg.hover")},`,
    `    bgSelected: ${at("bg.selected")},`,
    `    border: ${at("border.default")},`,
    `    borderSoft: ${at("border.soft")},`,
    `    fg: ${at("fg.default")},`,
    `    fgMuted: ${at("fg.muted")},`,
    `    fgFaint: ${at("fg.faint")},`,
    `    danger: ${at("danger")},`,
    `    switchOff: ${at("switch-off")},`,
    `    synString: ${at("syn-string")},`,
  ].join("\n");
}

// A platform layer declares only what it overrides; everything else falls
// through to the base layer, exactly as the CSS cascade resolves it.
function platformValue(get, platform, overridePath, basePath) {
  if (platform === "mac") return get(basePath);
  try {
    return get(`platform.${platform}.shared.${overridePath}`);
  } catch {
    return get(basePath);
  }
}

function typeTokens(get, platform) {
  const p = (overridePath, basePath) => platformValue(get, platform, overridePath, basePath);
  const step = (key) =>
    `{ size: ${quote(p(`ui.${key}`, `base.ui.${key}`))}, lineHeight: ${quote(
      p(`ui.${key}-lh`, `base.ui.${key}-lh`),
    )} }`;
  const heading = (key) =>
    `{ size: ${quote(p(`${key}.size`, `base.${key}.size`))}, weight: ${Number(
      p(`${key}.weight`, `base.${key}.weight`),
    )}, lineHeight: ${Number(p(`${key}.lh`, `base.${key}.lh`))} }`;
  return [
    `    fontUi: ${quote(p("font.ui", "base.font.ui"))},`,
    `    fontProse: ${quote(p("font.prose", "base.font.prose"))},`,
    `    fontProseAlt: ${quote(get("base.font.prose-alt"))},`,
    `    fontMono: ${quote(p("font.mono", "base.font.mono"))},`,
    `    ui: { xs: ${step("xs")}, sm: ${step("sm")}, md: ${step("md")}, lg: ${step("lg")} },`,
    `    uiTracking: ${quote(get("base.ui.tracking"))},`,
    `    prose: {`,
    `      size: ${quote(p("prose.size", "base.prose.size"))},`,
    `      lineHeight: ${quote(p("prose.lh", "base.prose.lh"))},`,
    `      measure: ${quote(get("base.prose.measure"))},`,
    `      padX: ${quote(get("base.prose.pad-x"))},`,
    `      padY: ${quote(get("base.prose.pad-y"))},`,
    `      pSpacing: ${quote(get("base.prose.p-spacing"))},`,
    `    },`,
    `    headingSpacing: ${quote(get("base.heading.spacing"))},`,
    `    headings: {`,
    ...["h1", "h2", "h3", "h4", "h5", "h6"].map((h) => `      ${h}: ${heading(h)},`),
    `    },`,
  ].join("\n");
}

function radiusTokens(get, platform) {
  const keys = [
    "row",
    "control",
    "tab",
    "popover",
    "modal",
    "card",
    "media",
    "pill",
    "action",
    "indicator",
    "window",
  ];
  return keys
    .map(
      (key) =>
        `    ${key}: ${quote(platformValue(get, platform, `r.${key}`, `base.r.${key}`))},`,
    )
    .join("\n");
}

StyleDictionary.registerFormat({
  name: "typescript/writ-tokens",
  format: ({ dictionary }) => {
    const get = tsLookup(dictionary);
    const accentTriple = (id, polarity) =>
      `{ base: ${quote(get(`accent.${id}.${polarity}.base`))}, hover: ${quote(
        get(`accent.${id}.${polarity}.hover`),
      )}, foreground: ${quote(get(`accent.${id}.${polarity}.foreground`))} }`;
    const shadowSet = (polarity) =>
      [
        `    popover: ${quote(get(`color.${polarity}.shadow.popover`))},`,
        `    modal: ${quote(get(`color.${polarity}.shadow.modal`))},`,
        `    chip: ${quote(get(`color.${polarity}.shadow.chip`))},`,
      ].join("\n");

    return `${BANNER_TS}

export type Polarity = "light" | "dark";
export type AccentId = ${ACCENT_IDS.map(quote).join(" | ")};
export type PlatformId = ${PLATFORM_IDS.map(quote).join(" | ")};
export type ProseFace = "system" | "quattro";

export interface AccentTriple {
  base: string;
  hover: string;
  foreground: string;
}

/** Every colour token name, per polarity, as a resolved CSS colour string. */
export interface ColorTokens {
  bgCanvas: string;
  bgSidebar: string;
  bgRaised: string;
  bgSunken: string;
  bgHover: string;
  bgSelected: string;
  border: string;
  borderSoft: string;
  fg: string;
  fgMuted: string;
  fgFaint: string;
  danger: string;
  switchOff: string;
  synString: string;
}

export interface TypeScaleStep {
  size: string;
  lineHeight: string;
}

export interface HeadingStep {
  size: string;
  weight: number;
  lineHeight: number;
}

export interface TypeTokens {
  fontUi: string;
  fontProse: string;
  fontProseAlt: string;
  fontMono: string;
  ui: { xs: TypeScaleStep; sm: TypeScaleStep; md: TypeScaleStep; lg: TypeScaleStep };
  uiTracking: string;
  prose: {
    size: string;
    lineHeight: string;
    measure: string;
    padX: string;
    padY: string;
    pSpacing: string;
  };
  headingSpacing: string;
  headings: {
    h1: HeadingStep;
    h2: HeadingStep;
    h3: HeadingStep;
    h4: HeadingStep;
    h5: HeadingStep;
    h6: HeadingStep;
  };
}

export interface RadiusTokens {
  row: string;
  control: string;
  tab: string;
  popover: string;
  modal: string;
  card: string;
  media: string;
  pill: string;
  action: string;
  indicator: string;
  window: string;
}

export interface MotionTokens {
  fast: string;
  base: string;
  slow: string;
  ease: string;
}

export interface ZTokens {
  base: number;
  chrome: number;
  popover: number;
  palette: number;
  modal: number;
  toast: number;
  drag: number;
}

export interface ShadowTokens {
  popover: string;
  modal: string;
  chip: string;
}

export const COLORS: Readonly<Record<Polarity, ColorTokens>> = {
  light: {
${colorTokens(get, "light")}
  },
  dark: {
${colorTokens(get, "dark")}
  },
};

export const ACCENTS: Readonly<Record<AccentId, Record<Polarity, AccentTriple>>> = {
${ACCENT_IDS.map(
  (id) =>
    `  ${objectKey(id)}: {\n    light: ${accentTriple(id, "light")},\n    dark: ${accentTriple(
      id,
      "dark",
    )},\n  },`,
).join("\n")}
};

export const SHADOWS: Readonly<Record<Polarity, ShadowTokens>> = {
  light: {
${shadowSet("light")}
  },
  dark: {
${shadowSet("dark")}
  },
};

export const TYPE: Readonly<Record<PlatformId, TypeTokens>> = {
${PLATFORM_IDS.map((platform) => `  ${platform}: {\n${typeTokens(get, platform)}\n  },`).join("\n")}
};

export const RADII: Readonly<Record<PlatformId, RadiusTokens>> = {
${PLATFORM_IDS.map((platform) => `  ${platform}: {\n${radiusTokens(get, platform)}\n  },`).join("\n")}
};

export const MOTION: Readonly<MotionTokens> = {
  fast: ${quote(get("base.motion.fast"))},
  base: ${quote(get("base.motion.duration"))},
  slow: ${quote(get("base.motion.slow"))},
  ease: ${quote(get("base.ease"))},
};

export const Z: Readonly<ZTokens> = {
  base: ${Number(get("base.z.base"))},
  chrome: ${Number(get("base.z.chrome"))},
  popover: ${Number(get("base.z.popover"))},
  palette: ${Number(get("base.z.palette"))},
  modal: ${Number(get("base.z.modal"))},
  toast: ${Number(get("base.z.toast"))},
  drag: ${Number(get("base.z.drag"))},
};

export const ICON: Readonly<{
  size: Record<PlatformId, string>;
  opacity: string;
  opacityHover: string;
}> = {
  size: {
${PLATFORM_IDS.map(
  (platform) =>
    `    ${platform}: ${quote(platformValue(get, platform, "icon.size", "base.icon.size"))},`,
).join("\n")}
  },
  opacity: ${quote(get("base.icon.opacity"))},
  opacityHover: ${quote(get("base.icon.opacity-hover"))},
};

export const SIDEBAR: Readonly<{
  width: string;
  rowPitch: Record<PlatformId, string>;
  rowFill: Record<PlatformId, string>;
  minWidth: string;
  maxWidth: string;
}> = {
  width: ${quote(get("base.sidebar.width"))},
  rowPitch: {
${PLATFORM_IDS.map(
  (platform) =>
    `    ${platform}: ${quote(
      platformValue(get, platform, "sidebar.row-pitch", "base.sidebar.row-pitch"),
    )},`,
).join("\n")}
  },
  rowFill: {
${PLATFORM_IDS.map(
  (platform) =>
    `    ${platform}: ${quote(
      platformValue(get, platform, "sidebar.row-fill", "base.sidebar.row-fill"),
    )},`,
).join("\n")}
  },
  minWidth: ${quote(get("base.sidebar.min-width"))},
  maxWidth: ${quote(get("base.sidebar.max-width"))},
};

export const SPACE: Readonly<{
  s1: string;
  s2: string;
  s3: string;
  s4: string;
  s5: string;
  s6: string;
  s7: string;
}> = {
${[1, 2, 3, 4, 5, 6, 7].map((n) => `  s${n}: ${quote(get(`base.space.${n}`))},`).join("\n")}
};

/**
 * CSS custom-property NAMES, not values. Anything that must react to a live
 * theme switch (cm-theme, inline styles) references these through \`var()\`;
 * never bake a value from COLORS into a stylesheet.
 */
export const CSS_VAR = {
  bgCanvas: "--writ-bg-canvas",
  bgSidebar: "--writ-bg-sidebar",
  bgRaised: "--writ-bg-raised",
  bgSunken: "--writ-bg-sunken",
  bgHover: "--writ-bg-hover",
  bgSelected: "--writ-bg-selected",
  border: "--writ-border",
  borderSoft: "--writ-border-soft",
  fg: "--writ-fg",
  fgMuted: "--writ-fg-muted",
  fgFaint: "--writ-fg-faint",
  accent: "--writ-accent",
  accentHover: "--writ-accent-hover",
  accentFg: "--writ-accent-fg",
  danger: "--writ-danger",
  synString: "--writ-syn-string",
  fontUi: "--writ-font-ui",
  fontProse: "--writ-font-prose",
  fontMono: "--writ-font-mono",
  proseSize: "--writ-prose-size",
  proseLineHeight: "--writ-prose-lh",
  proseMeasure: "--writ-prose-measure",
  prosePadX: "--writ-prose-pad-x",
  prosePadY: "--writ-prose-pad-y",
  headingColor: "--writ-heading-color",
  headingFormatting: "--writ-heading-formatting",
  rControl: "--writ-r-control",
  rMedia: "--writ-r-media",
  motion: "--writ-motion",
} as const;

/** \`var(--name)\`, or \`var(--name, fallback)\`. */
export function cssVar(name: string, fallback?: string): string {
  return fallback === undefined ? \`var(\${name})\` : \`var(\${name}, \${fallback})\`;
}
`;
  },
});

export default {
  usesDtcg: true,
  // The same custom property is emitted under several selectors by design
  // (polarity, platform and accent layers), which Style Dictionary reports as a
  // name collision. Broken references stay an error.
  log: { warnings: "disabled" },
  source: ["design/tokens/**/*.json"],
  platforms: {
    css: {
      transforms: ["value/dimension-css", "value/shadow-css", "name/writ-css"],
      buildPath: "src/styles/generated/",
      files: [{ destination: "theme.css", format: "css/writ-theme" }],
    },
    ts: {
      transforms: ["value/dimension-css", "value/shadow-css", "name/writ-ts"],
      buildPath: "src/styles/generated/",
      files: [{ destination: "tokens.ts", format: "typescript/writ-tokens" }],
    },
    "preview-css": {
      transforms: ["value/dimension-css", "value/shadow-css", "name/writ-preview-css"],
      buildPath: "src-tauri/assets/generated/",
      files: [{ destination: "preview-tokens.css", format: "css/writ-preview" }],
    },
    "site-css": {
      transforms: ["value/dimension-css", "value/shadow-css", "name/writ-css"],
      buildPath: "site/design-system/generated/",
      files: [{ destination: "tokens.css", format: "css/writ-site" }],
    },
  },
};
